* Encoding: UTF-8.
GLM RBTOIT1 RBTOIT2 BY GROUP WITH SEX
  /WSFACTOR=time 2 Polynomial
  /MEASURE=TEST
  /METHOD=SSTYPE(3)
  /PLOT=PROFILE(time*GROUP) TYPE=LINE ERRORBAR=NO MEANREFERENCE=NO YAXIS=AUTO
  /EMMEANS=TABLES(OVERALL) WITH(SEX=MEAN)
  /EMMEANS=TABLES(GROUP) WITH(SEX=MEAN)COMPARE ADJ(LSD)
  /EMMEANS=TABLES(time) WITH(SEX=MEAN)COMPARE ADJ(LSD)
  /EMMEANS=TABLES(GROUP*time) WITH(SEX=MEAN) COMPARE(GROUP) ADJ(LSD)
  /EMMEANS=TABLES(GROUP*time) WITH(SEX=MEAN) COMPARE(time) ADJ(LSD)
  /PRINT=DESCRIPTIVE ETASQ HOMOGENEITY
  /CRITERIA=ALPHA(.05)
  /WSDESIGN=time
  /DESIGN=SEX GROUP.

GLM ECOGT1 ECOGT2 BY GROUP
  /WSFACTOR=time 2 Polynomial
  /MEASURE=TEST
  /METHOD=SSTYPE(3)
  /PLOT=PROFILE(time*GROUP) TYPE=LINE ERRORBAR=NO MEANREFERENCE=NO YAXIS=AUTO
  /EMMEANS=TABLES(OVERALL)
  /EMMEANS=TABLES(GROUP) COMPARE ADJ(LSD)
  /EMMEANS=TABLES(time) COMPARE ADJ(LSD)
  /EMMEANS=TABLES(GROUP*time) COMPARE(GROUP) ADJ(LSD)
  /EMMEANS=TABLES(GROUP*time) COMPARE(time) ADJ(LSD)
  /PRINT=DESCRIPTIVE ETASQ HOMOGENEITY
  /CRITERIA=ALPHA(.05)
  /WSDESIGN=time
  /DESIGN=GROUP.

GLM ADRITT1 ADRITT2 BY GROUP
  /WSFACTOR=time 2 Polynomial
  /MEASURE=TEST
  /METHOD=SSTYPE(3)
  /PLOT=PROFILE(time*GROUP) TYPE=LINE ERRORBAR=NO MEANREFERENCE=NO YAXIS=AUTO
  /EMMEANS=TABLES(OVERALL)
  /EMMEANS=TABLES(GROUP) COMPARE ADJ(LSD)
  /EMMEANS=TABLES(time) COMPARE ADJ(LSD)
  /EMMEANS=TABLES(GROUP*time) COMPARE(GROUP) ADJ(LSD)
  /EMMEANS=TABLES(GROUP*time) COMPARE(time) ADJ(LSD)
  /PRINT=DESCRIPTIVE ETASQ HOMOGENEITY
  /CRITERIA=ALPHA(.05)
  /WSDESIGN=time
  /DESIGN=GROUP.

GLM ADRIPT1 ADRIPT2 BY GROUP
  /WSFACTOR=time 2 Polynomial
  /MEASURE=TEST
  /METHOD=SSTYPE(3)
  /PLOT=PROFILE(time*GROUP) TYPE=LINE ERRORBAR=NO MEANREFERENCE=NO YAXIS=AUTO
  /EMMEANS=TABLES(OVERALL)
  /EMMEANS=TABLES(GROUP) COMPARE ADJ(LSD)
  /EMMEANS=TABLES(time) COMPARE ADJ(LSD)
  /EMMEANS=TABLES(GROUP*time) COMPARE(GROUP) ADJ(LSD)
  /EMMEANS=TABLES(GROUP*time) COMPARE(time) ADJ(LSD)
  /PRINT=DESCRIPTIVE ETASQ HOMOGENEITY
  /CRITERIA=ALPHA(.05)
  /WSDESIGN=time
  /DESIGN=GROUP.

GLM ADRIRT1 ADRIRT2 BY GROUP
  /WSFACTOR=time 2 Polynomial
  /MEASURE=TEST
  /METHOD=SSTYPE(3)
  /PLOT=PROFILE(time*GROUP) TYPE=LINE ERRORBAR=NO MEANREFERENCE=NO YAXIS=AUTO
  /EMMEANS=TABLES(OVERALL)
  /EMMEANS=TABLES(GROUP) COMPARE ADJ(LSD)
  /EMMEANS=TABLES(time) COMPARE ADJ(LSD)
  /EMMEANS=TABLES(GROUP*time) COMPARE(GROUP) ADJ(LSD)
  /EMMEANS=TABLES(GROUP*time) COMPARE(time) ADJ(LSD)
  /PRINT=DESCRIPTIVE ETASQ HOMOGENEITY
  /CRITERIA=ALPHA(.05)
  /WSDESIGN=time
  /DESIGN=GROUP.